module.exports.menus = [
  {
    text:"线索",
    url:"/pages/thread/thread",
    icon:"/icons/thread.png",
  },
  {
    text:"客户",
    url:"/pages/customer/customer",
    icon:"/icons/customer.png",
  },
  {
    text:"联系人",
    url:"/pages/contact/contact",
    icon:"/icons/contact.png",
  },
  {
    text:"商机",
    url:"/pages/business/business",
    icon:"/icons/business.png",
  },
  {
    text:"合同",
    url:"/pages/contracts/contracts",
    icon:"/icons/contract.png",
  },
  {
    text:"产品",
    url:"/pages/product/product",
    icon:"/icons/product.png",
  },
  {
    text:"回款",
    url:"/pages/paid/paid",
    icon:"/icons/payment.png",
  },
  {
    text:"日程",
    url:"/pages/agenda/agenda",
    icon:"/icons/agenda.png"
  },
];