module.exports.mynav = [
  {
    text:"产品",
    url:"/pages/myproduct/myproduct",
  },
  {
    text:"商机",
    url:"/pages/mybusiness/mybusiness",
  },
  {
    text:"线索",
    url:"/pages/mythread/mythread",
  },
  {
    text:"回款",
    url:"/pages/mypayment/mypayment",
  },
  {
    text:"合同",
    url:"/pages/mycontract/mycontract",
  }
];